### ISSUE TITLE
Please creae a DFRobot Repo

### ISSUE THREAD

**Issue by askpatrickw** [creationid/creators#12]
Related to #11 ... a DF Robot repo is needed to track creations (or is it?) Maybe there's an easier way to do this?

**Comment by tannewt** [comment]
Maybe we just have a "Community" repo that covers all community done ones.

**Comment by askpatrickw** [comment]
For now I created DF-Robot.

But yeah, I coudl see merging all these into a Community with a markdown H1 for each Creator ID and H2 for each Chipset, etc... or I know you love TOML. If you ever plan to validate or enforce these things..

**Comment by tannewt** [comment]
@askpatrickw I'm open to either. toml would work but it'd be nice to render it into something human friendly (like markdown does.)

**Comment by tannewt** [comment]
dfrobot repo is here: https://github.com/creationid/dfrobot-creations
