### ISSUE TITLE
Proposal for Community Management of Creators and Creations

### ISSUE THREAD

**Issue by askpatrickw** [creationid/creators#13]
Following up on a conversation with Scott... 

Today, _my_ assumption is that a Creator would come and update README here to reserve namespace on a CreatorID and then self-host someplace else a list of CreationIDs.

The rest of this is about creators and creations where the person working on the CP port is not the manufacturer\designer of the board.

In those cases, the community is maintaining both of these, so having a repo per Creator is hard to manage as they probably should live in this Org not in the contributors personal namespace. But creating repos is more complicated than a PR.

creationid/creatrors/README.md is the list of Creators and a link to where the Creations for that creator live. If its a repo in another place, great. But if not, then a `creationid/creators/creations/CREATOR_NAME.md` should be created in this repo and that is what is linked to in the README.md.

So if we look at my most recent addition:
`0x1010_1010 [DFRobot](https://github.com/creationid/dfrobot-creations)`

I needed a repo in this org.

Instead it would be 
`0x1010_1010 [DFRobot](creations/DFROBOT.md)`

Not sure my markdown is correct, but that is intended to be a link to a DFROBOT.md in a creations folder in this repo.

This should let people add both CreatorIDs and CreationIDs with a PR and not need to ask for repos.

Let me know what you think.  I'm happy to make PRs for all the repos we would want to move to whatever final format we decide.

**Comment by askpatrickw** [comment]
Let me know what you think @tannewt ty!

**Comment by tannewt** [comment]
@askpatrickw Yup, I think that's a great idea. Let me know if you need anything from me to make it happen.

**Comment by tannewt** [comment]
I'll do this now. I need a HardKernel one.
