### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by gitcnd** [creationid/creators#65]
Circuitpython links here for non-native-usb builds.

e.g. .../ports/espressif/boards]$ head m5stack_timer_camera_x/mpconfigboard.mk
CIRCUITPY_CREATOR_ID =  0x10151015
CIRCUITPY_CREATION_ID = 0x00320009

The "creators/README.md" is extremely unclear, with no mention of how to register new IDs, who should do this, what ID's to use (random?) when to put an underscore in the middle of what is supported to be hex, etc etc.

It would be a good idea to update the readme so that every newcomer to this page is given every bit of information they could possibly need to use it.

For context - I'm just a techy contributor (not a manufacturer) and I'm writing board definition ports, where these codes are mandatory... sometimes I know who designs and/or makes the boards I'm porting, other times I do not (aliexpress cheapies and knockoffs, some of which are not 100% compatible with whatever they copied from).  I've no idea if "creator" needs to be me, the designer, or the manufacturer, (or something else...)

**Comment by tannewt** [comment]
I'll revise the docs tomorrow. Thanks!
