### ISSUE TITLE
Create wemos-creations Repo

### ISSUE THREAD

**Issue by askpatrickw** [creationid/creators#8]
related: https://github.com/creationid/creators/pull/7#issuecomment-1106716537, https://github.com/adafruit/circuitpython/pull/6256

Every Creator needs a place to keep Creations.
Since WEMOS is a company who publishes many boards, I propose a wemos-creations Repo be created in this organization.

**Comment by tannewt** [comment]
Done: https://github.com/creationid/wemos-creations Sorry for the delay, I was on paternity leave.
